theme: jekyll-theme-minimal

title: [My Road 2 InfoSec]
description: [On 1/5/2020 i decided to switch my career into the infosec sector as non IT leteral entrant. I decided to document my journey. So follow along on this wild ride]
#logo: []
