theme: jekyll-theme-minimal

title: [My Road 2 InfoSec]
description: [On 01/05/2020 I decided to switch my career into the InfoSec sector as non IT leteral entrant. I decided to document my journey. So follow along on this wild ride. It will be bumpy!]
logo: assets/img/mimiclynx02.png
